version: 1
disable_existing_loggers: False
formatters:
  default:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
handlers:
  console_handler:
    class: logging.StreamHandler
    level: ERROR
    formatter: default
    stream: ext://sys.stdout
  info_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: default
    filename: info.log
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8
loggers:
  datamodel_logger:
    level: INFO
    handlers: [info_file_handler]
    propagate: no
  parser_logger:
    level: INFO
    handlers: [info_file_handler]
    propagate: no
  test_parser_logger:
    level: INFO
    handlers: [info_file_handler]
    propagate: no
root:
    level: ERROR
    handlers: [console_handler, info_file_handler]
    propagate: yes


